### ISSUE TITLE
Vertically stretched thumbnails in the popup

### ISSUE THREAD

**Issue by vlakoff** [tnychn/media-controller-extension#15]
I noticed vertically streched thumbnails in the popup.

To address this, here is the code I figured out:

* in [index.js](https://github.com/tnychn/media-controller-extension/blob/main/src/popup/index.js):

```html
<div class="tab-thumbnail">
  <img src="...">
</div>
```

* in [index.css](https://github.com/tnychn/media-controller-extension/blob/main/src/popup/index.css):

```css
.tab-thumbnail {
  width: 30%;
  background-color: #000;
  display: flex;
  align-items: center;
  justify-content: center;
}

.tab-thumbnail > img {
  max-width: 100%;
  max-height: 100%;
}
```

This works with both "landscape" and "portrait" images.

By the way, in the current HTML, the `width="100%" height="100%"` is erroneous: these attributes are for the intrinsic dimensions of the image, and should contain only integers. Refs: [`width`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#width) and [`height`](
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#height) attributes. That's a very common mistake.
